# Site wide configuration

title: "XLinBoy's Blog"
description: "我的学习历程"
logo: logo.jpg # 120x120 px default image used for Twitter summary card
teaser: /teaser/default.jpg # 400x250 px default teaser image used in image archive grid
locale:
url:

default:
    -
        scope:
            type: "article"
        values:
            ads: false
            toc: false 


# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner: 
  name: XLinBoy
  email: 13135797896@163.com
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: xlin


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
